server:
  port: 8085

spring:
  application:
    name: execution-coordinator

  datasource:
    url: jdbc:h2:mem:execution;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.distributed.jobscheduler: DEBUG
