server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: job-store-service

  datasource:
    url: jdbc:h2:mem:jobstore;MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.distributed.jobscheduler: DEBUG
    org.hibernate.SQL: DEBUG
